on:
  push:
    branches: [main]
    paths-ignore:
      - 'tests/*.golden'

jobs:
  run-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tests
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Run test_validate_url
        id: test
        run: |
          pytest file_test.py::test_validate_url
        continue-on-error: true

  update-golden-files:
    needs: run-test
    if: needs.run-test.result == 'failure'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tests
    steps:
      - name: Check out repository with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get Golden File Content
        id: get_content
        run: |
          response=$(curl -s https://bsky.app/profile/witheringtales.bsky.social/post/3legkyuzjs22)
          echo "response=$response" >> $GITHUB_OUTPUT
      - name: Update Golden Files
        run: |
          echo "${{ steps.get_content.outputs.response }}" > no_content_template.golden
      - name: Commit changes
        run: |
          git config user.name c985-star
          git config user.email c4746376@gmail.com
          git add *.golden
          git commit -am "Golden Files Updated" || echo "No changes to commit"
          git push
