name: Issue assignment

on:
    issues:
        types: [opened]
    pull_request:
        types: [opened]

jobs:
    auto-assign:
        runs-on: ubuntu-latest
        permissions:
            issues: write
        steps:
            - name: 'Auto-assign issue'
              uses: pozil/auto-assign-issue@v1
              with:
                  assignees: andewmark,Lementknight
                  numOfAssignee: 1
                  allowSelfAssign: true